name: Build and Deploy via FTP

on:
  push:
    branches:
      - main # change to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up PHP for Laravel
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql, curl, tokenizer, xml

      # 3. Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # 4. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 5. Install Node modules & build React assets
      - name: Build frontend assets
        run: |
          npm ci
          npm run build

      # 6. Optional: Clear Laravel caches
      # - name: Clear Laravel caches
      #   run: |
      #     php artisan cache:clear
      #     php artisan config:clear
      #     php artisan route:clear
      #     php artisan view:clear

      # 7. Deploy files via FTP
      - name: Deploy via FTP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          source: './'
          target: '/public_html/'
